# Use root/Gh4nO7!#ft user/password credentials
version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
    env_file: .env
    environment:
      - DB=${DB}
      - HOST=${HOST}
      - DB_ROOT=${DB_ROOT}
      - DB_ADMIN=${DB_ADMIN}
      - DB_MANAGER=${DB_MANAGER}
      - DB_USER=${DB_USER}
      - DB_NOT_USER=${DB_NOT_USER}
      - PASS_ROOT=${PASS_ROOT}
      - PASS_ADMIN=${PASS_ADMIN}
      - PASS_MANAGER=${PASS_MANAGER}
      - PASS_USER=${PASS_USER}
      - PASS_NOT_USER=${PASS_NOT_USER}

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gh4nO7!#ft
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data:
